ALTER TABLE demandeami
DROP
COLUMN iddemande;

ALTER TABLE demandeami
DROP
COLUMN idemetteur;

ALTER TABLE demandeami
DROP
COLUMN idrecepteur;

ALTER TABLE demandeami
    ADD iddemande BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE demandeami
    ADD idemetteur BIGINT NOT NULL;

ALTER TABLE demandeami
    ADD CONSTRAINT FK_DEMANDEAMI_ON_IDEMETTEUR FOREIGN KEY (idemetteur) REFERENCES utilisateur (idutilisateur);

ALTER TABLE demandeami
    ADD idrecepteur BIGINT NOT NULL;

ALTER TABLE demandeami
    ADD CONSTRAINT FK_DEMANDEAMI_ON_IDRECEPTEUR FOREIGN KEY (idrecepteur) REFERENCES utilisateur (idutilisateur);

ALTER TABLE demandeami
    ALTER COLUMN statutdemande SET NOT NULL;